version: "3.8"

volumes:
  postgres:

services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-aulas"
    ports:
      - "9999:9999"
      - "3333:3333"
      - "5555:5555"
      - "51204:51204"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm start"

  db-03:
    image: bitnami/postgresql
    container_name: "rocketseat-nodejs-aulas-db-03"
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: apisolid
    volumes:
      - postgres:/data/postgres
