version: "3.8"
services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-aulas"
    ports:
      - "9999:9999"
      - "3333:3333"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm start"
