volumes:
  postgres:
  postgres-05:
  redis-05:

services:
  app:
    image: node:20.17.0
    container_name: "rocketseat-nodejs-aulas"
    ports:
      - "9999:9999"
      - "3333:3333"
      - "5555:5555"
      - "51204:51204"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm start"

  db-03:
    image: bitnami/postgresql
    container_name: "rocketseat-nodejs-aulas-db-03"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: apisolid
    volumes:
      - postgres:/data/postgres

  db-05:
    image: bitnami/postgresql
    container_name: "rocketseat-nodejs-aulas-db-05"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: nestclean
    volumes:
      - postgres-05:/data/postgres

  redis-05:
    image: redis
    container_name: "rocketseat-nodejs-aulas-redis-05"
    ports:
      - "6375:6379"
    volumes:
      - redis-05:/data
