version: "3.8"
services:
  app:
    image: node:latest
    container_name: "rocketseat-nodejs-02-api-rest"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm i && npm run dev"
