name: 03 API SOLID Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03-api-solid
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        working-directory: ./03-api-solid
        with:
          node-version: 20
          cache: 'npm'
      
      - run: npm ci
        working-directory: ./03-api-solid
      
      - run: npm run test
        working-directory: ./03-api-solid
